title: Daniel Rodríguez
description: Matemáticas · Investigación · Escritos personales

remote_theme: mmistakes/minimal-mistakes

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-remote-theme
