locale: "en-US"
title: Daniel Rodriguez
description: Matemáticas · Investigación · Escritos personales
minimal_mistakes_skin: air
layout: single

author:
  name: Daniel Rodriguez
  avatar:
  bio: >
    Mathematician - Number Theory.
Academic and personal writings.
remote_theme: mmistakes/minimal-mistakes

markdown: kramdown
kramdown:
  math_engine: mathjax
header:
  nav: main
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
