title: Daniel Rodriguez
description: Matemáticas · Investigación · Escritos personales
minimal_mistakes_skin: air
layout: single

author:
  name: Daniel Rodriguez
  avatar:
  bio: >
    Matemático. Teoría de números.
    Escritos académicos y personales.
remote_theme: mmistakes/minimal-mistakes

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
